"""arXiv's LaTeXML HTML to markdown: ``papers.latexml``.

Fixtures are trimmed from real renderings (1706.03762v7, hep-th/9901001) —
class names, nesting and the page chrome around the article kept as served.
"""

from hypothesis import given, settings
from hypothesis import strategies as st

from academic_tools_mcp.papers import latexml, sections

_CHROME_HEAD = (
    "<!DOCTYPE html><html><head><title>Attention Is All You Need</title>"
    "<script>window.x = 1;</script></head><body>"
    '<dialog id="modal-form"><h5 class="modal-title">Report GitHub Issue</h5></dialog>'
    '<header><nav class="html-header-nav"><a class="header-button">Why HTML?</a></nav></header>'
    '<div class="ltx_page_main"><div class="ltx_page_content">'
)
_CHROME_TAIL = (
    '</div></div><footer class="arxiv-html-footer"><div class="ltx_page_logo">'
    "Generated by LaTeXML</div></footer></body></html>"
)


def _page(article: str) -> str:
    return f'{_CHROME_HEAD}<article class="ltx_document">{article}</article>{_CHROME_TAIL}'


_ATTENTION = _page(
    '<h1 class="ltx_title ltx_title_document">Attention Is All You Need</h1>'
    '<div class="ltx_authors"><span class="ltx_creator ltx_role_author">'
    '<span class="ltx_personname">Ashish Vaswani</span>'
    '<span class="ltx_note ltx_role_thanks"><sup class="ltx_note_mark">†</sup>'
    '<span class="ltx_note_outer"><span class="ltx_note_content">'
    '<sup class="ltx_note_mark">†</sup><span class="ltx_note_type">thanks: </span>'
    "Equal contribution.</span></span></span></span></div>"
    '<nav class="ltx_TOC"><ol class="ltx_toclist"><li class="ltx_tocentry">'
    '<span class="ltx_ref_title">1 Introduction</span></li></ol></nav>'
    '<div class="ltx_abstract"><h6 class="ltx_title ltx_title_abstract">Abstract</h6>'
    '<p class="ltx_p">The dominant sequence transduction models are\n  based on RNNs.</p></div>'
    '<section id="S1" class="ltx_section">'
    '<h2 class="ltx_title ltx_title_section"><span class="ltx_tag ltx_tag_section">1 </span>'
    "Introduction</h2>"
    '<div class="ltx_para"><p class="ltx_p">Recurrent neural networks '
    '<cite class="ltx_cite">[<a href="#bib.bib13" class="ltx_ref">13</a>]</cite> map '
    '<math class="ltx_Math" alttext="(x_{1},...,x_{n})" display="inline">'
    "<semantics><mrow><mi>x</mi></mrow>"
    '<annotation encoding="application/x-tex">(x_{1},...,x_{n})</annotation>'
    "</semantics></math> to outputs.</p></div>"
    "</section>"
    '<section id="S3" class="ltx_section">'
    '<h2 class="ltx_title ltx_title_section">3 Model Architecture</h2>'
    '<section id="S3.SS2" class="ltx_subsection">'
    '<h3 class="ltx_title ltx_title_subsection">3.2 Attention</h3>'
    '<section class="ltx_subsubsection">'
    '<h4 class="ltx_title ltx_title_subsubsection">3.2.1 Scaled Dot-Product Attention</h4>'
    '<div class="ltx_para"><table id="S3.E1" class="ltx_equation ltx_eqn_table"><tbody>'
    '<tr class="ltx_equation ltx_eqn_row">'
    '<td class="ltx_eqn_cell ltx_eqn_center_padleft"></td>'
    '<td class="ltx_eqn_cell ltx_align_center">'
    '<math class="ltx_Math" alttext="\\mathrm{Attention}(Q,K,V)=\\mathrm{softmax}(\\frac{QK^{T}}'
    '{\\sqrt{d_{k}}})V" display="block"><mi>A</mi></math></td>'
    '<td class="ltx_eqn_cell ltx_eqn_center_padright"></td>'
    '<td class="ltx_eqn_cell ltx_eqn_eqno"><span class="ltx_tag ltx_tag_equation">(1)</span></td>'
    "</tr></tbody></table></div>"
    '<h5 class="ltx_title ltx_title_paragraph">Encoder:</h5>'
    "</section></section>"
    '<figure id="S3.F1" class="ltx_figure"><img src="x/ModalNet-21.png" alt="Refer to caption">'
    '<figcaption class="ltx_caption"><span class="ltx_tag ltx_tag_figure">Figure 1: </span>'
    "The Transformer - model architecture.</figcaption></figure>"
    '<figure id="S4.T1" class="ltx_table">'
    '<figcaption class="ltx_caption"><span class="ltx_tag">Table 2: </span>BLEU.</figcaption>'
    '<table class="ltx_tabular"><thead class="ltx_thead">'
    '<tr class="ltx_tr"><th class="ltx_th" rowspan="2">Model</th>'
    '<th class="ltx_th" colspan="2">BLEU</th><th class="ltx_th">Cost</th></tr></thead>'
    '<tbody class="ltx_tbody"><tr class="ltx_tr"><td class="ltx_td">ByteNet</td>'
    '<td class="ltx_td">23.75</td><td class="ltx_td">a|b</td>'
    '<td class="ltx_td"><math alttext="1.0\\cdot 10^{20}" display="inline"></math></td></tr>'
    "</tbody></table></figure>"
    '<ul class="ltx_itemize"><li class="ltx_item"><div class="ltx_para">'
    '<p class="ltx_p">First point.</p></div></li>'
    '<li class="ltx_item"><p class="ltx_p">Second point.</p></li></ul>'
    "</section>"
    '<section class="ltx_bibliography">'
    '<h2 class="ltx_title ltx_title_bibliography">References</h2>'
    '<ul class="ltx_biblist"><li id="bib.bib1" class="ltx_bibitem">'
    '<span class="ltx_tag ltx_tag_bibitem">[1]</span>'
    '<span class="ltx_bibblock">\nJimmy Lei Ba.\n</span>'
    '<span class="ltx_bibblock">Layer normalization.\n</span></li></ul></section>'
)


class TestDocumentStructure:
    def test_headings_land_on_the_levels_sections_reads(self):
        md = latexml.to_markdown(_ATTENTION)
        headings = [line for line in md.split("\n") if line.startswith("#")]

        assert headings == [
            "# Attention Is All You Need",
            "## Abstract",
            "## 1 Introduction",
            "## 3 Model Architecture",
            "### 3.2 Attention",
            "#### 3.2.1 Scaled Dot-Product Attention",
            "#### Encoder:",
            "## References",
        ]

    def test_the_section_index_is_detected_with_sub_headings(self):
        index, detected = sections.parse_sections_and_detect(latexml.to_markdown(_ATTENTION))

        assert detected is True
        titles = [s["title"] for s in index]
        assert titles[-4:] == ["Abstract", "1 Introduction", "3 Model Architecture", "References"]
        model = next(s for s in index if s["title"] == "3 Model Architecture")
        assert model["h3s"] == ["3.2 Attention"]

    def test_page_chrome_and_the_toc_are_not_rendered(self):
        md = latexml.to_markdown(_ATTENTION)

        for chrome in ("Report GitHub Issue", "Why HTML?", "Generated by LaTeXML", "window.x"):
            assert chrome not in md
        # The TOC entry would otherwise duplicate the section heading as text.
        assert md.count("1 Introduction") == 1

    def test_paragraph_whitespace_collapses(self):
        md = latexml.to_markdown(_ATTENTION)

        assert "The dominant sequence transduction models are based on RNNs." in md


class TestMath:
    def test_inline_math_is_its_latex_source_once(self):
        md = latexml.to_markdown(_ATTENTION)

        assert "Recurrent neural networks [13] map $(x_{1},...,x_{n})$ to outputs." in md
        # The MathML annotation carries the same TeX; it must not be read twice.
        assert md.count("x_{1}") == 1

    def test_a_display_equation_is_its_own_block_with_its_number(self):
        md = latexml.to_markdown(_ATTENTION)

        assert (
            "\n\n$$\\mathrm{Attention}(Q,K,V)=\\mathrm{softmax}(\\frac{QK^{T}}"
            "{\\sqrt{d_{k}}})V$$ (1)\n\n"
        ) in md

    def test_escaped_alttext_is_unescaped(self):
        html = _page('<p><math alttext="a&amp;b\\\\\nc" display="inline"></math></p>')

        assert latexml.to_markdown(html) == "$a&b\\\\ c$\n"

    def test_math_without_alttext_renders_nothing(self):
        assert latexml.to_markdown(
            _page('<p>x <math display="inline"><mi>y</mi></math> z</p>')
        ) == ("x z\n")


class TestFiguresTablesListsNotes:
    def test_images_drop_and_captions_stay(self):
        md = latexml.to_markdown(_ATTENTION)

        assert "Figure 1: The Transformer - model architecture." in md
        assert "ModalNet" not in md
        assert "Refer to caption" not in md

    def test_a_tabular_becomes_a_pipe_table_aligned_across_a_colspan(self):
        md = latexml.to_markdown(_ATTENTION)

        assert (
            "| Model | BLEU |  | Cost |\n"
            "| --- | --- | --- | --- |\n"
            "| ByteNet | 23.75 | a\\|b | $1.0\\cdot 10^{20}$ |"
        ) in md

    def test_list_items_and_bibliography_entries_are_one_line_each(self):
        md = latexml.to_markdown(_ATTENTION)

        assert "- First point.\n\n- Second point." in md
        assert "- [1] Jimmy Lei Ba. Layer normalization." in md

    def test_a_footnote_reads_inline_without_its_marks(self):
        md = latexml.to_markdown(_ATTENTION)

        assert "Ashish Vaswani [thanks: Equal contribution.]" in md
        assert "†" not in md

    def test_undefined_macro_errors_are_dropped(self):
        html = _page('<p>YITP-99-1 <span class="ltx_ERROR undefined">\\recdate</span>August</p>')

        assert latexml.to_markdown(html) == "YITP-99-1 August\n"


class TestDegenerateInput:
    def test_no_article_renders_the_whole_page(self):
        assert latexml.to_markdown("<p>Just text.</p>") == "Just text.\n"

    def test_empty_input_is_empty_output(self):
        assert latexml.to_markdown("") == ""
        assert latexml.to_markdown(_page("")) == ""

    def test_unbalanced_tags_do_not_lose_text(self):
        html = _page("<section><h2 class='ltx_title_section'>1 A</h2><p>one<p>two</em></span>three")

        md = latexml.to_markdown(html)

        assert md.startswith("## 1 A\n\n")
        for word in ("one", "two", "three"):
            assert word in md


@settings(max_examples=200, deadline=None)
@given(st.text())
def test_arbitrary_text_never_raises(text):
    assert isinstance(latexml.to_markdown(text), str)


@settings(max_examples=100, deadline=None)
@given(
    st.lists(
        st.sampled_from(
            [
                "<p>",
                "</p>",
                "<table>",
                "<tr>",
                "<td>",
                "</td>",
                "</table>",
                "<math alttext='x'>",
                "</math>",
                "<h2 class='ltx_title_section'>",
                "</h2>",
                "<ul>",
                "<li>",
                "text",
                "&amp;",
            ]
        ),
        max_size=60,
    )
)
def test_arbitrary_tag_soup_never_raises(parts):
    assert isinstance(latexml.to_markdown(_page("".join(parts))), str)
